---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-sd-role
rules:
  - apiGroups: [ "" ]
    resources: [ "services","endpoints","pods" ]
    verbs: [ "list","get", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-sd-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-sd-role
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: app-mon
